# Generated by Django 4.2.5 on 2023-10-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrole',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='usersrole',
            old_name='user',
            new_name='user_id',
        ),
    ]
